version: '2'
services:
  app:
    image: docit/codecreation
    container_name: cc.site
    ports:
      - "8083:80"
    volumes:
      - ../../shared/sites/default/settings.php:/var/www/web/sites/default/settings.php
      - ../../shared/sites/default/services.yml:/var/www/web/sites/default/services.yml
      - ../../shared/sites/default/files:/var/www/web/sites/default/files